[[constraint]]
  version = "v1.3.3"
  #branch = "master"
  name = "go.mongodb.org/mongo-driver"

[[constraint]]
  branch = "master"
  name = "github.com/simagix/gox"

[[constraint]]
  version = "v0.5.4"
  #branch = "master"
  name = "github.com/simagix/mongo-atlas"

[[constraint]]
  version = "v1.0.2-rc0"
  #branch = "dev"
  name = "github.com/simagix/mongo-ftdc"

[[override]]
  branch = "release-branch.go1.13"
  #branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "release-branch.go1.13"
  #branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
